controlplane $ k get serviceaccount -oyaml
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-06-08T06:10:26Z"
    name: default
    namespace: default
    resourceVersion: "390"
    uid: 448f3879-e9df-40f5-a3e4-dabac8587212
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: loki
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-06-19T05:53:32Z"
    labels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: loki
      app.kubernetes.io/version: 3.0.0
      helm.sh/chart: loki-6.6.3
    name: loki
    namespace: default
    resourceVersion: "2283"
    uid: 3965895a-5628-43d1-ba27-aa17a6754d06
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: loki
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-06-19T05:53:32Z"
    labels:
      app.kubernetes.io/component: canary
      app.kubernetes.io/instance: loki
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: loki
      app.kubernetes.io/version: 3.0.0
      helm.sh/chart: loki-6.6.3
    name: loki-canary
    namespace: default
    resourceVersion: "2284"
    uid: 552ca26b-d5aa-4de4-9ba5-319078651d67
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: loki
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-06-19T05:53:32Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: minio-sa
    namespace: default
    resourceVersion: "2285"
    uid: e89f2c31-695b-4506-a3af-281bd60a14f0
kind: List
metadata:
  resourceVersion: ""
controlplane $ 
