apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: node01
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2024-06-19T05:53:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    name: data-loki-backend-0
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: loki-backend
      uid: 2ff12b81-3e90-42a7-bc27-b0f662a33012
    resourceVersion: "2753"
    uid: 73d18624-e462-4f19-8578-12604fd92205
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-73d18624-e462-4f19-8578-12604fd92205
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: controlplane
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2024-06-19T05:53:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    name: data-loki-backend-1
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: loki-backend
      uid: 2ff12b81-3e90-42a7-bc27-b0f662a33012
    resourceVersion: "2700"
    uid: ee67f3ca-2375-4791-96d4-fc002c5a4152
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-ee67f3ca-2375-4791-96d4-fc002c5a4152
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: node01
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2024-06-19T05:53:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: write
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    name: data-loki-write-0
    namespace: default
    resourceVersion: "2744"
    uid: ed013ba4-f97b-43dd-bf5e-5569169f6242
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-ed013ba4-f97b-43dd-bf5e-5569169f6242
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: controlplane
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2024-06-19T05:53:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: write
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    name: data-loki-write-1
    namespace: default
    resourceVersion: "2639"
    uid: 92d8ef5f-09e8-4dae-a4b8-ab6d308a8980
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-92d8ef5f-09e8-4dae-a4b8-ab6d308a8980
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: controlplane
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2024-06-19T05:53:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: minio
      release: loki
    name: export-0-loki-minio-0
    namespace: default
    resourceVersion: "2630"
    uid: 408f6603-1c32-40a7-89a5-7b08e61566c0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-408f6603-1c32-40a7-89a5-7b08e61566c0
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: controlplane
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2024-06-19T05:53:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: minio
      release: loki
    name: export-1-loki-minio-0
    namespace: default
    resourceVersion: "2710"
    uid: cfbf5e91-23b3-4833-9b7a-3abdf7a791ce
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-cfbf5e91-23b3-4833-9b7a-3abdf7a791ce
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
